### ISSUE TITLE
Function parameters don't receive types which causes an error

### ISSUE THREAD

**Issue by jskrzypek** [englercj/tsd-jsdoc#22]
I was trying to generate a declaration file for `https://github.com/twilio/twilio-video.js` and I got this error.

```
Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:408
            switch (e.kind) {
                     ^

TypeError: Cannot read property 'kind' of null
    at writeReference (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:408:22)
    at writeParameter (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:508:9)
    at writeDelimited (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:517:13)
    at writeFunction (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:496:9)
    at writeDeclaration (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:673:28)
    at Object.emit (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:241:5)
    at Emitter.emit (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/tsd-jsdoc/Emitter.js:65:24)
    at Object.publish (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/tsd-jsdoc/publish.js:25:39)
    at Object.module.exports.cli.generateDocs (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:180:5)
    at /Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by jskrzypek** [comment]
Wow, that was fast! I'll test tomorrow, thanks!

**Comment by englercj** [comment]
You just happened to post right when I was working on this lib :P

**Comment by jskrzypek** [comment]
Now it's happening with class members, it seems...
```
/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:408
            switch (e.kind) {
                     ^

TypeError: Cannot read property 'kind' of null
    at writeReference (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:408:22)
    at writePropertyDeclaration (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:576:9)
    at writeClassMember (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:559:24)
    at writeClass (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:549:13)
    at writeDeclaration (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:679:28)
    at Object.emit (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/dts-dom/bin/index.js:241:5)
    at Emitter.emit (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/tsd-jsdoc/Emitter.js:65:24)
    at Object.publish (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/tsd-jsdoc/publish.js:25:39)
    at Object.module.exports.cli.generateDocs (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/cli.js:180:5)
    at /Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/Users/jskrzypek/dev/twilio/twilio-video.js/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by englercj** [comment]
Damn, guess I should've reran on the entire file and not just the problem area. Sorry about that.

I'll take a look when I can (this weekend?)

**Comment by jskrzypek** [comment]
I started working on some improvements, they're on my fork

**Comment by jskrzypek** [comment]
Specifically, I'm getting​ around the error above by doing this: https://github.com/jskrzypek/tsd-jsdoc/commit/bdb1b66b9610b1b8e49a878e23ca2073cd3db5fb
