### ISSUE TITLE
Crashes when encountering comment blocks

### ISSUE THREAD

**Issue by macleodbroad-wf** [englercj/tsd-jsdoc#31]
When running against a file that contains comment blocks ~~without jsdoc tags~~ directly above a variable declaration that does not reference a function or class:
```
/**
 * Following label is used in the settings to describe values which should be
 * determined by the code while running, from the current data and graph style.
 *
 * Using 'undefined' directly achieves the same thing, but this is more
 * descriptive by describing the intent.
 */
var autoByDefault = undefined;
```
It appears to crash with:
```
/Users/mbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:268
    throw new Error(err);
    ^

Error: Unknown declaration kind property
    at never (/Users/mbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:268:11)
    at writeDeclaration (/Users/mbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:780:28)
    at Object.emit (/Users/mbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:276:5)
    at Emitter.emit (/Users/mbroad/workspaces/vis/node_modules/tsd-jsdoc/Emitter.js:65:24)
    at Object.publish (/Users/mbroad/workspaces/vis/node_modules/tsd-jsdoc/publish.js:25:39)
    at Object.module.exports.cli.generateDocs (/usr/local/lib/node_modules/jsdoc/cli.js:448:35)
    at Object.module.exports.cli.processParseResults (/usr/local/lib/node_modules/jsdoc/cli.js:399:20)
    at module.exports.cli.main (/usr/local/lib/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:189:5)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

I've been able to work around the issue by adding the `@ignore` tag to the comment block.

**Comment by englercj** [comment]
Thanks for the report, I'll make sure to handle this more gracefully.

**Comment by englercj** [comment]
v2 was just released and this seems to be working as expected now.
