### ISSUE TITLE
`@constructor` or `@class` in jsdoc above a function declaration crashes

### ISSUE THREAD

**Issue by macleodbroad-wf** [englercj/tsd-jsdoc#32]
When encountering a top-level function where the `@constructor` or `@class` tag is used in the jsdoc:
```
/**
 * An ItemSet holds a set of items and ranges which can be displayed in a
 * range. The width is determined by the parent of the ItemSet, and the height
 * is determined by the size of the items.
 * @param {{dom: Object, domProps: Object, emitter: Emitter, range: Range}} body
 * @param {Object} [options]      See ItemSet.setOptions for the available options.
 * @constructor ItemSet
 * @extends Component
 */
function ItemSet(body, options) {
  this.body = body;
  ...
}
```

Crashes with exception:
```
/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:471
            switch (e.kind) {
                     ^

TypeError: Cannot read property 'kind' of null
    at writeReference (/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:471:22)
    at writePropertyDeclaration (/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:647:9)
    at writeClassMember (/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:630:24)
    at writeClass (/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:620:13)
    at writeDeclaration (/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:760:28)
    at Object.emit (/Users/macleodbroad/workspaces/vis/node_modules/dts-dom/bin/index.js:276:5)
    at Emitter.emit (/Users/macleodbroad/workspaces/vis/node_modules/tsd-jsdoc/Emitter.js:65:24)
    at Object.publish (/Users/macleodbroad/workspaces/vis/node_modules/tsd-jsdoc/publish.js:25:39)
    at Object.module.exports.cli.generateDocs (/usr/local/lib/node_modules/jsdoc/cli.js:448:35)
    at Object.module.exports.cli.processParseResults (/usr/local/lib/node_modules/jsdoc/cli.js:399:20)
    at module.exports.cli.main (/usr/local/lib/node_modules/jsdoc/cli.js:240:14)
    at Object.module.exports.cli.runCommand (/usr/local/lib/node_modules/jsdoc/cli.js:189:5)
    at /usr/local/lib/node_modules/jsdoc/jsdoc.js:105:9
    at Object.<anonymous> (/usr/local/lib/node_modules/jsdoc/jsdoc.js:106:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
```

Can work around it by removing the `@constructor` or `@class` tag.

**Comment by englercj** [comment]
Looks like this is no longer happening in the latest v2
