### ISSUE TITLE
Pixi.js-v5

### ISSUE THREAD

**Issue by ivanpopelyshev** [englercj/tsd-jsdoc#57]
Suppose you've cloned pixi.js, `dev` branch, and called tsd-jsdoc on `packages`. Don't call `npm run build` or you'll ruin it with unnecessary files. That's the output:

```
d:\pixi-games\tsd-jsdoc\Emitter.js:196
                    for (let i = 0; i < doclet.params.length; ++i) {
                                                      ^

TypeError: Cannot read property 'length' of undefined
    at Emitter._resolveObjects (d:\pixi-games\tsd-jsdoc\Emitter.js:196:55)
    at Emitter.parse (d:\pixi-games\tsd-jsdoc\Emitter.js:58:14)
```

We have to specify external classes somewhere:

```
[TSD-JSDoc] Unable to resolve type name "Float32Array". No type found with that name, defaulting to "any".
[TSD-JSDoc] Unable to resolve type name "Float32Array". No type found with that name, defaulting to "any".
```

**Comment by englercj** [comment]
Are you sure you are using the latest version? That error message doesn't even exist in v2.

**Comment by englercj** [comment]
Closing this since he was on an earlier version.
